### ISSUE TITLE
Filter out unreferenced gene and submitter data in test data output

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clinvar-scv#16]
Currently all gene and submitter data is included in test data output by default. This ends up causing unneccessary burden on the test data loading process used in development. Filter out the genes and submitters not referenced anywhere in the selected set of variants/scvs/etc in the dataset.

**Comment by theferrit32** [comment]
Issue moved to [clingen-data-model/clinvar-streams #14](https://github.com/clingen-data-model/clinvar-streams/issues/14) via [**ZenHub**](https://www.zenhub.com/)
